import { useState } from "react";
import type { ReactNode } from "react";

const steps = [
  ["1", "Describe the setup", "Write naturally or begin with a tested template. Choose exchange, timeframe, universe and risk limits."],
  ["2", "Review the interpretation", "Inspect every rule, assumption and unsupported term. Edit or clarify anything before it can run."],
  ["3", "Approve and preview", "Run the rules over recent data. Activation remains locked until you approve the exact strategy version."],
  ["4", "Monitor, then decide", "Receive forming and confirmed setup alerts with evidence. You verify the opportunity and choose what to do."],
];

const chips = ["AND / OR rule groups", "Multi-timeframe filters", "Technical indicators", "Candlestick patterns", "Price action", "Volume and liquidity filters", "Spread and listing-age filters", "Optional entry, stop and target context", "Optional reward-to-risk validation", "Candle close or intrabar", "Cooldowns and deduplication", "Forward testing", "Recent-market preview", "Chart snapshots", "Performance analytics"];

const faqs = [
  ["Does it place trades for me?", "No. Version one does not connect to exchange trading APIs or execute orders. It monitors, explains and alerts; every trading decision remains yours."],
  ["Does AI decide whether a setup passed?", "No. AI can translate your description and explain deterministic results. Indicator calculations and rule outcomes come from the rule engine, and you must approve the structured interpretation."],
  ["Can I use more than one timeframe?", "Yes. A 15-minute entry can depend on a four-hour trend filter or other declared supporting timeframes."],
  ["What if my setup is subjective?", "The interpretation identifies ambiguous or unsupported terms and asks you to define them. A strategy cannot activate while those issues remain unresolved."],
  ["Are alerts guaranteed to be accurate or immediate?", "No. Exchange outages, network delay, incomplete data and software failures can affect results. Each receipt exposes candle timing and data freshness so you can verify it."],
];

function Logo() {
  return <div className="flex items-center gap-3"><div className="grid size-9 place-items-center rounded-[10px] bg-gradient-to-br from-[#c4b5fd] to-[#8b5cf6] text-[11px] font-semibold text-white tracking-[-0.04em]">AM</div><span className="text-[16px] font-medium text-[#3a3a46]">TraceEdge</span></div>;
}

function Button({ children, subtle = false }: { children: ReactNode; subtle?: boolean }) {
  return <button className={subtle ? "min-h-[50px] rounded-[13px] border border-black/10 bg-white px-6 font-display font-bold text-[#0b0b10] transition hover:-translate-y-0.5 hover:border-[#8b5cf6]/40" : "min-h-[50px] rounded-[13px] bg-gradient-to-br from-[#a78bfa] to-[#8b5cf6] px-6 font-display font-bold text-white shadow-[0_16px_21px_rgba(139,92,246,.34)] transition hover:-translate-y-0.5"}>{children}</button>;
}

function WatchlistCard() {
  const pairs = [["SOL / USDT", "Improving", "85%", "w-[85%]", "#66F9A1"], ["LINK / USDT", "Stable", "70%", "w-[70%]", "#2A5ADA"], ["ETH / USDT", "Weakening", "55%", "w-[55%]", "#627EEA"]];
  return <div className="relative mx-auto w-full max-w-[454px] overflow-hidden rounded-[26px] border border-[#4b3669]/15 bg-[#f7f3ff] shadow-[0_24px_70px_rgba(75,54,105,.16)]">
    <div className="flex h-[50px] items-center justify-between border-b border-[#4b3669]/15 bg-white px-[18px] text-[11px] font-bold text-[#3a3a46]"><div className="flex gap-1.5"><i className="size-2 rounded bg-[#d8caff]"/><i className="size-2 rounded bg-[#c4b5fd]"/><i className="size-2 rounded bg-[#a78bfa]"/></div><span>Lifecycle Watchlist</span><span className="text-[9px] font-normal">Live example</span></div>
    <div className="flex items-center justify-between border-b border-[#4b3669]/15 bg-white p-5"><div><p className="font-bold text-[#3a3a46]">Liquidity Sweep + Trend</p><p className="text-xs text-[#3a3a46]">Binance spot · 15m</p></div><span className="rounded-full bg-[#9167f7] px-3 py-2 text-[10px] font-extrabold text-[#f9f7ff]">Scanning 342 pairs</span></div>
    <div className="space-y-0.5 bg-white p-[18px]">{pairs.map((p) => <div key={p[0]} className="flex items-center justify-between rounded-xl border border-[#c4b5fd]/20 bg-[#c4b5fd]/10 p-3"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-[11px] bg-white shadow-[0_8px_22px_rgba(75,54,105,.14)]"><i style={{ backgroundColor: p[4] }} className="size-7 rounded-full" /></span><span><b className="block text-[13px] text-[#3a3a46]">{p[0]}</b><small className="text-[10px] text-[#656579]">{p[1]}</small></span></div><div className="flex w-[120px] items-center gap-2 text-xs font-bold text-[#9167f7]"><span>{p[2]}</span><span className="h-[5px] flex-1 rounded bg-[#e0d8ff]"><i className={`${p[3]} block h-full rounded bg-[#9167f7]`} /></span></div></div>)}</div>
    <div className="bg-white px-[18px] pb-[18px]"><div className="rounded-[15px] border border-[#c4b5fd]/30 bg-[#9167f7] p-[18px] text-white shadow-[0_22px_30px_rgba(0,0,0,.24)]"><div className="flex justify-between"><b>SOL/USDT</b><span className="text-[11px] text-[#e0d8ff]">Near confirmation</span></div>{[["4h close above EMA 200", "$146.82 > $142.10", "PASS"], ["Bullish liquidity sweep", "Prior low reclaimed", "PASS"], ["Volume at least 1.5x", "1.36x / 1.50x", "MISSING"]].map((r) => <div key={r[0]} className="flex justify-between border-t border-white/10 py-2.5 text-[11px]"><span>{r[0]}<small className="block text-[9px] text-[#e0d8ff]">{r[1]}</small></span><b className="text-[10px] text-[#c4b5fd]">{r[2]}</b></div>)}<p className="pt-1 text-[9px] text-[#e0d8ff]">Candle closed 14:45 UTC · Data fresh 1.8s ago</p></div></div>
  </div>;
}

export default function App() {
  const [open, setOpen] = useState(0);
  return <main className="min-h-screen bg-[#f7f7fa] text-[#0b0b10] font-sans selection:bg-[#c4b5fd]/50">
    <section className="mx-auto grid max-w-[1180px] gap-14 px-5 py-20 lg:min-h-[740px] lg:grid-cols-[1fr_454px] lg:items-center lg:px-0"><div><p className="mb-5 flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.12em] text-[#a78bfa]"><i className="size-2 rounded bg-[#a78bfa]"/> Personal market monitoring, explained</p><h1 className="max-w-[650px] font-display text-[clamp(42px,6vw,56px)] leading-[.98] tracking-[-.04em]">See your setup forming before it confirms.</h1><p className="mt-5 max-w-xl text-[19px] leading-[1.55] text-[#3a3a46]">Describe your setup once. TraceEdge scans spot markets and explains each forming lifecycle.</p><div className="mt-8 flex flex-wrap gap-3"><Button>Sign up →</Button><Button subtle>How it works</Button></div><div className="mt-7 flex flex-wrap gap-x-6 gap-y-2 text-[13px] text-[#3a3a46]"><span className="text-[#8b5cf6]">✓</span>No trading API keys <span className="text-[#8b5cf6]">✓</span>No automatic execution <span className="text-[#8b5cf6]">✓</span>You make every decision</div></div><WatchlistCard /></section>
    <div className="bg-gradient-to-b from-[#a78bfa] to-[#8b5cf6] px-5 py-[18px] text-center text-xs font-bold uppercase tracking-[.08em] text-[#f7f3ff] shadow-[0_22px_32px_rgba(139,92,246,.26)]"><div className="mx-auto flex max-w-[1180px] flex-wrap justify-center gap-x-[60px] gap-y-3"><span>Built for crypto spot traders</span><span>Multi-timeframe rules</span><span>Telegram + Discord</span><span>Condition-level proof</span></div></div>
    <section className="mx-auto max-w-[1180px] px-5 py-24 lg:px-0"><p className="eyebrow">From idea to monitor</p><h2 className="section-title">Your setup, translated into rules you can inspect.</h2><p className="section-copy">AI helps structure what you mean. A deterministic scanner handles every market calculation after you approve it.</p><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{steps.map((s) => <article className="rounded-[22px] border border-black/10 bg-white p-[29px]" key={s[0]}><span className="grid size-[46px] place-items-center rounded-xl bg-gradient-to-br from-[#c4b5fd] to-[#8b5cf6] text-sm font-bold text-white">{s[0]}</span><h3 className="mt-12 font-display text-xl font-bold tracking-[-.045em]">{s[1]}</h3><p className="mt-3 text-sm leading-[1.55] text-[#3a3a46]">{s[2]}</p></article>)}</div></section>
    <section className="mx-auto max-w-[1180px] px-5 py-20 lg:px-0"><p className="eyebrow">Monitoring toolkit</p><h2 className="section-title max-w-[800px]">The standard capabilities serious monitoring needs.</h2><div className="mt-12 flex flex-wrap gap-2.5">{chips.map(c => <span className="rounded-full border border-black/10 px-4 py-3 text-[13px] font-semibold text-[#3a3a46]" key={c}>{c}</span>)}</div></section>
    <section className="mx-auto grid max-w-[1180px] gap-8 px-5 py-20 lg:grid-cols-[486px_1fr] lg:px-0"><div><p className="eyebrow">Alerts where they belong</p><h2 className="section-title text-[clamp(38px,5vw,52px)]">Start quickly in Telegram. Go deeper on the web.</h2><p className="mt-8 text-[17px] leading-[1.55] text-[#3a3a46]">Telegram is the fastest path to onboarding and immediate alerts. The web dashboard supports detailed strategy editing, proof tables, analytics and billing.</p><div className="mt-8"><Button>Join the trace →</Button></div></div><div className="grid gap-3 sm:grid-cols-2"><DarkCard title="Telegram" copy="Primary onboarding, alerts and quick setup status."/><DarkCard title="Discord" copy="Optional alert channels, community and role management."/><div className="sm:col-span-2"><DarkCard title="Web dashboard" copy="Advanced rules, analytics, lifecycles and account controls."/></div></div></section>
    <section className="mx-auto max-w-[1180px] px-5 py-24 text-center lg:px-0"><p className="eyebrow justify-center">Configurable plans</p><h2 className="section-title mx-auto">Choose the monitoring capacity you need.</h2><p className="section-copy mx-auto">Plans are constrained by active strategies, monitored symbols, scan frequency and advanced features, not by promises of trading results.</p><div className="mt-12 grid gap-4 lg:grid-cols-3"><Plan name="Demo / Free" price="$0" cta="Start free" items={["One active monitor", "Up to 50 spot pairs", "15-minute timeframe or higher", "Telegram only"]}/><Plan featured name="Pro" price="$29" cta="Start Pro Trial" items={["Up to 10 active strategies", "All supported spot pairs", "Telegram and Discord alerts", "Lifecycle and forensic history"]}/><Plan name="Creator / Community" price="$79+" cta="Contact us" items={["Shared templates and channels", "Discord role integration", "Community delivery", "White-label options by plan"]}/></div></section>
    <section className="mx-auto grid max-w-[1180px] gap-10 px-5 py-20 lg:grid-cols-[436px_1fr] lg:px-0"><div><p className="eyebrow">Questions, answered plainly</p><h2 className="section-title">What TraceEdge does and does not do.</h2></div><div>{faqs.map((f, i) => <button onClick={() => setOpen(open === i ? -1 : i)} className="block w-full border-b border-black/10 py-5 text-left" key={f[0]}><span className="flex justify-between font-extrabold tracking-[-.015em]">{f[0]}<b className="text-[#8b5cf6]">{open === i ? "−" : "+"}</b></span>{open === i && <p className="pt-4 leading-[1.55] text-[#3a3a46]">{f[1]}</p>}</button>)}</div></section>
    <section className="mx-auto max-w-[1180px] px-5 py-20 lg:px-0"><div className="rounded-[30px] border border-[#c4b5fd]/25 bg-white px-8 py-20 text-center"><p className="eyebrow justify-center">Stop checking every chart</p><h2 className="font-display text-[clamp(38px,6vw,62px)] leading-[1.08] tracking-[-.045em]">Teach the monitor what matters to you.</h2><p className="mt-4 text-[#3a3a46]">Build your first structured setup, inspect the interpretation and preview it on recent market data.</p><div className="mt-7"><Button>Join us →</Button></div></div><div className="mt-14 rounded-[15px] border border-[#c4b5fd]/25 bg-white p-7 text-left text-[13px] leading-[1.7] text-[#3a3a46] sm:grid sm:grid-cols-[160px_1fr]"><b className="text-[#9167f7]">Risk disclaimer</b><p>TraceEdge is a market-monitoring and decision-support product, not a broker, exchange, fiduciary or source of guaranteed financial advice. Alerts may be delayed, incomplete or incorrect. Crypto assets are volatile and trading can result in substantial loss. Verify all data independently and make your own decisions. The platform does not execute trades in version one.</p></div></section>
    <footer className="mt-10 border-t border-[#c4b5fd]/15 bg-[#111114] px-5 py-16 text-[#e6e6eb]"><div className="mx-auto grid max-w-[1180px] gap-10 md:grid-cols-[2fr_1fr_1fr_1fr]"><div><Logo/><p className="mt-5 max-w-sm text-white/70">Explainable crypto market monitoring for individual traders.</p></div>{["Product", "Legal", "Support"].map((h, idx) => <div key={h}><b>{h}</b><div className="mt-4 grid gap-3 text-[#8b5cf6]"><span>{idx === 0 ? "Features" : idx === 1 ? "Risk disclosure" : "Contact support"}</span><span>{idx === 0 ? "Pricing" : idx === 1 ? "Terms" : "Help center"}</span><span>{idx === 0 ? "FAQ" : idx === 1 ? "Privacy" : ""}</span></div></div>)}</div><div className="mx-auto mt-12 flex max-w-[1180px] justify-between border-t border-white/10 pt-5 text-white/80"><span>© 2026 TraceEdge</span><span>Monitoring, not automatic trading.</span></div></footer>
  </main>;
}

function DarkCard({ title, copy }: { title: string; copy: string }) { return <article className="rounded-[18px] border border-black/10 bg-[#17131f] p-[26px] text-[#f7f3ff]"><span className="grid size-10 place-items-center rounded-xl bg-white text-[#9167f7] font-extrabold">{title[0]}</span><h3 className="mt-5 font-display text-[19px] font-bold">{title}</h3><p className="mt-2 text-[13px] leading-[1.55]">{copy}</p></article>; }
function Plan({ name, price, cta, items, featured = false }: { name: string; price: string; cta: string; items: string[]; featured?: boolean }) { return <article className={featured ? "rounded-[22px] bg-gradient-to-br from-[#7760ba] to-[#170a34] p-[31px] text-left text-white shadow-[0_24px_35px_rgba(70,45,110,.14)]" : "rounded-[22px] border border-black/10 bg-white p-[31px] text-left text-[#3a3a46]"}><h3 className="font-display text-xl font-bold">{name}</h3><p className="mt-5 min-h-[54px] font-display">{featured ? "Full individual monitoring with Telegram, Discord and lifecycle evidence." : name.includes("Demo") ? "A light way to understand the monitor before upgrading." : "Shared strategy workflows for creators and private communities."}</p><div className="my-5 text-[29px] font-bold tracking-[-.045em] text-current">{price} <span className="text-xs">/ month</span></div><Button subtle={!featured}>{cta}</Button><ul className="mt-8 space-y-4 text-sm">{items.map(i => <li key={i}><span className={featured ? "text-[#e0d8ff]" : "text-[#8b5cf6]"}>✓</span> {i}</li>)}</ul></article>; }
