"""Durable operational measurements

``operational_metric_deltas`` holds each process's movement on each metric for
each window. Its unique key includes ``writer`` so no two processes ever share a
row, which is what removes the read-modify-write race entirely: a process writes
only what it added, and a reader adds the rows up.

Written by hand rather than autogenerated. Autogenerate on this repository also
picks up unrelated reflection differences on SQLite, and a migration that quietly
carries someone else's change is a migration nobody can review.

Revision ID: 3ba17c6d40f2
Revises: c1f4a7b20e93
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3ba17c6d40f2"
down_revision: str | None = "c1f4a7b20e93"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "operational_metric_deltas",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("metric_name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("label_signature", sa.String(length=500), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("writer", sa.String(length=120), nullable=False),
        sa.Column("total", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("buckets", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "metric_name",
            "label_signature",
            "window_start",
            "writer",
            name="uq_operational_metric_delta_series",
        ),
    )
    op.create_index(
        "ix_operational_metric_delta_window",
        "operational_metric_deltas",
        ["window_start", "metric_name"],
    )
    op.create_index(
        "ix_operational_metric_delta_name_window",
        "operational_metric_deltas",
        ["metric_name", "window_start"],
    )


def downgrade() -> None:
    # The table holds only measurements. Nothing customer-owned and nothing another
    # table points at, so dropping it loses history and nothing else.
    op.drop_index(
        "ix_operational_metric_delta_name_window", table_name="operational_metric_deltas"
    )
    op.drop_index(
        "ix_operational_metric_delta_window", table_name="operational_metric_deltas"
    )
    op.drop_table("operational_metric_deltas")
