"""initial core schema

Revision ID: 5aa448aa1447
Revises: 
Create Date: 2026-06-14 21:33:40.759040
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5aa448aa1447'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_health',
    sa.Column('integration', sa.String(length=40), nullable=False),
    sa.Column('scope_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='integration_health_status', native_enum=False), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_health')),
    sa.UniqueConstraint('integration', 'scope_key', name='uq_integration_health_scope')
    )
    with op.batch_alter_table('integration_health', schema=None) as batch_op:
        batch_op.create_index('ix_integration_health_status_checked', ['status', 'checked_at'], unique=False)

    op.create_table('market_data_health',
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('market_type', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='market_health_status', native_enum=False), nullable=False),
    sa.Column('last_candle_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lag_seconds', sa.Integer(), nullable=True),
    sa.Column('missing_candle_count', sa.Integer(), nullable=False),
    sa.Column('error_rate', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_data_health')),
    sa.UniqueConstraint('exchange', 'market_type', 'timeframe', name='uq_market_health_scope')
    )
    with op.batch_alter_table('market_data_health', schema=None) as batch_op:
        batch_op.create_index('ix_market_health_status_checked', ['status', 'checked_at'], unique=False)

    op.create_table('plans',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_active_strategies', sa.Integer(), nullable=False),
    sa.Column('max_symbols_per_strategy', sa.Integer(), nullable=False),
    sa.Column('minimum_scan_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('discord_enabled', sa.Boolean(), nullable=False),
    sa.Column('backtest_enabled', sa.Boolean(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans')),
    sa.UniqueConstraint('code', name=op.f('uq_plans_code'))
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status', native_enum=False), nullable=False),
    sa.Column('role', sa.Enum('user', 'support', 'admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)

    op.create_table('audit_events',
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('metadata_redacted', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_created', ['actor_user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index('ix_audit_request', ['request_id'], unique=False)
        batch_op.create_index('ix_audit_target', ['target_type', 'target_id'], unique=False)

    op.create_table('billing_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('payload_redacted', sa.JSON(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_billing_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_events')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_billing_events_provider_event_id'))
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_events_processing_status'), ['processing_status'], unique=False)
        batch_op.create_index('ix_billing_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('discord_connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('discord_user_id', sa.String(length=64), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'error', name='discord_connection_status', native_enum=False), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_scopes', sa.JSON(), nullable=False),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discord_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_connections')),
    sa.UniqueConstraint('discord_user_id', name='uq_discord_user_id'),
    sa.UniqueConstraint('guild_id', 'channel_id', name='uq_discord_guild_channel')
    )
    with op.batch_alter_table('discord_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_discord_connections_user_id'), ['user_id'], unique=False)

    op.create_table('onboarding_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'blocked', 'completed', 'abandoned', name='onboarding_status', native_enum=False), nullable=False),
    sa.Column('current_step', sa.Enum('introduction', 'account', 'disclaimer', 'trial', 'guided_setup', 'interpretation', 'approval', 'validation', 'activation', 'complete', name='onboarding_step', native_enum=False), nullable=False),
    sa.Column('entry_channel', sa.String(length=32), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('blocked_reason', sa.String(length=500), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_onboarding_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_onboarding_sessions'))
    )
    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_onboarding_updated', ['updated_at'], unique=False)
        batch_op.create_index('ix_onboarding_user_status', ['user_id', 'status'], unique=False)

    op.create_table('referral_codes',
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_referral_codes_owner_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_codes')),
    sa.UniqueConstraint('code', name=op.f('uq_referral_codes_code'))
    )
    with op.batch_alter_table('referral_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_codes_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('strategies',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'archived', name='strategy_status', native_enum=False), nullable=False),
    sa.Column('active_version_id', sa.Uuid(), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_strategies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategies'))
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_user_status', ['user_id', 'status'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'trialing', 'active', 'past_due', 'canceled', 'expired', name='subscription_status', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_subscriptions_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('provider', 'provider_subscription_id', name='uq_provider_subscription')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index('ix_subscription_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_current_period_end'), ['current_period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_provider_customer_id'), ['provider_customer_id'], unique=False)

    op.create_table('support_requests',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_user_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending_user', 'in_progress', 'resolved', 'closed', name='support_request_status', native_enum=False), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_support_requests_assigned_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_support_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_requests'))
    )
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.create_index('ix_support_status_priority', ['status', 'priority'], unique=False)
        batch_op.create_index('ix_support_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('telegram_connections',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', 'error', name='connection_status', native_enum=False), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_connections_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_connections')),
    sa.UniqueConstraint('chat_id', name=op.f('uq_telegram_connections_chat_id')),
    sa.UniqueConstraint('telegram_user_id', name='uq_telegram_user_id'),
    sa.UniqueConstraint('user_id', name=op.f('uq_telegram_connections_user_id'))
    )
    op.create_table('user_identities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('email', 'telegram', 'discord', name='identity_provider', native_enum=False), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('normalized_identifier', sa.String(length=320), nullable=True),
    sa.Column('display_identifier', sa.String(length=320), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_data', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_identities')),
    sa.UniqueConstraint('provider', 'normalized_identifier', name='uq_identity_provider_identifier'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_identity_provider_subject')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_user_identities_user_provider', ['user_id', 'provider'], unique=False)

    op.create_table('attribution_touches',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('medium', sa.String(length=100), nullable=True),
    sa.Column('campaign', sa.String(length=160), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('referral_code', sa.String(length=64), nullable=True),
    sa.Column('entry_channel', sa.String(length=32), nullable=False),
    sa.Column('landing_path', sa.String(length=500), nullable=True),
    sa.Column('consented', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], name=op.f('fk_attribution_touches_onboarding_session_id_onboarding_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attribution_touches_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribution_touches'))
    )
    with op.batch_alter_table('attribution_touches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attribution_touches_campaign'), ['campaign'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribution_touches_onboarding_session_id'), ['onboarding_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribution_touches_referral_code'), ['referral_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribution_touches_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_attribution_touches_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_attribution_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('disclaimer_acceptances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identity_id', sa.Uuid(), nullable=False),
    sa.Column('disclaimer_version', sa.String(length=40), nullable=False),
    sa.Column('acceptance_source', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['user_identities.id'], name=op.f('fk_disclaimer_acceptances_identity_id_user_identities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_disclaimer_acceptances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disclaimer_acceptances')),
    sa.UniqueConstraint('user_id', 'disclaimer_version', name='uq_disclaimer_user_version')
    )
    with op.batch_alter_table('disclaimer_acceptances', schema=None) as batch_op:
        batch_op.create_index('ix_disclaimer_user_accepted', ['user_id', 'accepted_at'], unique=False)

    op.create_table('identity_link_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=False),
    sa.Column('token_digest', sa.String(length=64), nullable=False),
    sa.Column('target_channel', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], name=op.f('fk_identity_link_tokens_onboarding_session_id_onboarding_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_identity_link_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_identity_link_tokens')),
    sa.UniqueConstraint('token_digest', name=op.f('uq_identity_link_tokens_token_digest'))
    )
    with op.batch_alter_table('identity_link_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_link_token_user_expiry', ['user_id', 'expires_at'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'needs_clarification', 'approved', 'previewing', 'ready', 'active', 'superseded', 'rejected', name='strategy_version_status', native_enum=False), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('schema_version', sa.String(length=20), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('schema_hash', sa.String(length=64), nullable=False),
    sa.Column('interpretation_provider', sa.String(length=80), nullable=True),
    sa.Column('interpretation_model', sa.String(length=100), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('ambiguities', sa.JSON(), nullable=False),
    sa.Column('unsupported_conditions', sa.JSON(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('approved_schema_hash', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preview_status', sa.String(length=32), nullable=False),
    sa.Column('previewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preview_summary', sa.JSON(), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_strategy_versions_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_strategy_versions_strategy_id_strategies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_versions')),
    sa.UniqueConstraint('strategy_id', 'version_number', name='uq_strategy_version_number')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index('ix_strategy_schema_hash', ['schema_hash'], unique=False)
        batch_op.create_index('ix_strategy_version_status', ['strategy_id', 'status'], unique=False)

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_foreign_key(
            op.f('fk_strategies_active_version_id_strategy_versions'),
            'strategy_versions',
            ['active_version_id'],
            ['id'],
            ondelete='SET NULL',
        )

    op.create_table('trials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('active', 'converted', 'expired', 'canceled', name='trial_status', native_enum=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted_subscription_id', sa.Uuid(), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['converted_subscription_id'], ['subscriptions.id'], name=op.f('fk_trials_converted_subscription_id_subscriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_trials_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trials_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trials')),
    sa.UniqueConstraint('user_id', name=op.f('uq_trials_user_id'))
    )
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.create_index('ix_trial_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trials_ends_at'), ['ends_at'], unique=False)

    op.create_table('scan_jobs',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'partial', 'failed', 'canceled', name='scan_job_status', native_enum=False), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('symbols_planned', sa.Integer(), nullable=False),
    sa.Column('symbols_scanned', sa.Integer(), nullable=False),
    sa.Column('matches_found', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_scan_jobs_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_scan_jobs_idempotency_key'))
    )
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_scan_job_status_scheduled', ['status', 'scheduled_for'], unique=False)
        batch_op.create_index('ix_scan_job_version_created', ['strategy_version_id', 'created_at'], unique=False)

    op.create_table('strategy_conditions',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('parent_condition_id', sa.Uuid(), nullable=True),
    sa.Column('condition_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('condition_type', sa.Enum('indicator', 'price_action', 'candle_pattern', 'market_filter', 'risk', name='condition_type', native_enum=False), nullable=True),
    sa.Column('logical_operator', sa.Enum('and', 'or', name='logical_operator', native_enum=False), nullable=True),
    sa.Column('timeframe', sa.String(length=16), nullable=True),
    sa.Column('comparator', sa.String(length=32), nullable=True),
    sa.Column('left_operand', sa.JSON(), nullable=False),
    sa.Column('right_operand', sa.JSON(), nullable=False),
    sa.Column('required_value', sa.Numeric(precision=30, scale=10), nullable=True),
    sa.Column('weight', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_condition_id'], ['strategy_conditions.id'], name=op.f('fk_strategy_conditions_parent_condition_id_strategy_conditions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_strategy_conditions_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_conditions')),
    sa.UniqueConstraint('strategy_version_id', 'condition_key', name='uq_version_condition_key')
    )
    with op.batch_alter_table('strategy_conditions', schema=None) as batch_op:
        batch_op.create_index('ix_condition_version_parent', ['strategy_version_id', 'parent_condition_id'], unique=False)

    op.create_table('strategy_universes',
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('market_type', sa.Enum('spot', name='market_type', native_enum=False), nullable=False),
    sa.Column('quote_currencies', sa.JSON(), nullable=False),
    sa.Column('include_symbols', sa.JSON(), nullable=False),
    sa.Column('exclude_symbols', sa.JSON(), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=False),
    sa.Column('trigger_mode', sa.Enum('candle_close', 'intrabar', name='trigger_mode', native_enum=False), nullable=False),
    sa.Column('min_quote_volume_24h', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('min_listing_age_days', sa.Integer(), nullable=True),
    sa.Column('max_spread_bps', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('min_order_book_depth', sa.Numeric(precision=30, scale=8), nullable=True),
    sa.Column('max_symbols', sa.Integer(), nullable=True),
    sa.Column('scan_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_strategy_universes_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_universes')),
    sa.UniqueConstraint('strategy_version_id', name=op.f('uq_strategy_universes_strategy_version_id'))
    )
    op.create_table('scan_results',
    sa.Column('scan_job_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.Enum('confirmed', 'forming', 'near_miss', 'invalid', 'skipped', 'expired', 'error', name='scan_outcome', native_enum=False), nullable=False),
    sa.Column('completion_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('candle_closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_freshness_ms', sa.Integer(), nullable=False),
    sa.Column('is_candle_complete', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.String(length=160), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('proof_summary', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_scan_results_scan_job_id_scan_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_scan_results_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_results')),
    sa.UniqueConstraint('scan_job_id', 'exchange', 'symbol', 'timeframe', name='uq_scan_result_market')
    )
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.create_index('ix_scan_result_outcome_score', ['outcome', 'completion_score'], unique=False)
        batch_op.create_index('ix_scan_result_version_candle', ['strategy_version_id', 'candle_closed_at'], unique=False)

    op.create_table('setup_instances',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('latest_scan_result_id', sa.Uuid(), nullable=True),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('setup_key', sa.String(length=160), nullable=False),
    sa.Column('state', sa.Enum('detected', 'forming', 'near_confirmation', 'confirmed', 'entry_zone_active', 'entry_zone_missed', 'invalidated', 'expired', 'target_reached', 'stop_level_reached', 'closed', name='setup_lifecycle_state', native_enum=False), nullable=False),
    sa.Column('completion_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_zone_low', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('entry_zone_high', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('close_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['latest_scan_result_id'], ['scan_results.id'], name=op.f('fk_setup_instances_latest_scan_result_id_scan_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_setup_instances_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_setup_instances_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setup_instances')),
    sa.UniqueConstraint('strategy_version_id', 'exchange', 'symbol', 'timeframe', 'setup_key', name='uq_setup_instance_key')
    )
    with op.batch_alter_table('setup_instances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setup_instances_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_setup_strategy_state', ['strategy_version_id', 'state'], unique=False)
        batch_op.create_index('ix_setup_user_market', ['user_id', 'exchange', 'symbol'], unique=False)

    op.create_table('alerts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('setup_instance_id', sa.Uuid(), nullable=True),
    sa.Column('alert_type', sa.Enum('forming', 'near_miss', 'confirmed', 'lifecycle', 'failure', 'trial', name='alert_type', native_enum=False), nullable=False),
    sa.Column('deduplication_key', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('proof_receipt', sa.JSON(), nullable=False),
    sa.Column('chart_snapshot_url', sa.String(length=1000), nullable=True),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['setup_instance_id'], ['setup_instances.id'], name=op.f('fk_alerts_setup_instance_id_setup_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_alerts_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts')),
    sa.UniqueConstraint('deduplication_key', name='uq_alert_deduplication_key')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_setup_type', ['setup_instance_id', 'alert_type'], unique=False)
        batch_op.create_index('ix_alert_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('near_miss_snapshots',
    sa.Column('scan_result_id', sa.Uuid(), nullable=False),
    sa.Column('setup_instance_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('exchange', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=40), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('completion_score', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('previous_score', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('trend', sa.String(length=16), nullable=False),
    sa.Column('passed_condition_keys', sa.JSON(), nullable=False),
    sa.Column('missing_conditions', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], name=op.f('fk_near_miss_snapshots_scan_result_id_scan_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setup_instance_id'], ['setup_instances.id'], name=op.f('fk_near_miss_snapshots_setup_instance_id_setup_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_near_miss_snapshots_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_near_miss_snapshots')),
    sa.UniqueConstraint('scan_result_id', name='uq_near_miss_scan_result')
    )
    with op.batch_alter_table('near_miss_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_near_miss_market_captured', ['exchange', 'symbol', 'captured_at'], unique=False)
        batch_op.create_index('ix_near_miss_version_score', ['strategy_version_id', 'completion_score'], unique=False)

    op.create_table('setup_condition_results',
    sa.Column('setup_instance_id', sa.Uuid(), nullable=False),
    sa.Column('scan_result_id', sa.Uuid(), nullable=False),
    sa.Column('strategy_condition_id', sa.Uuid(), nullable=False),
    sa.Column('condition_key', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.Enum('passed', 'failed', 'pending', 'unavailable', 'error', name='condition_outcome', native_enum=False), nullable=False),
    sa.Column('required_value', sa.JSON(), nullable=False),
    sa.Column('actual_value', sa.JSON(), nullable=False),
    sa.Column('distance_to_pass', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('contribution_score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('candle_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_freshness_ms', sa.Integer(), nullable=False),
    sa.Column('explanation_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['scan_result_id'], ['scan_results.id'], name=op.f('fk_setup_condition_results_scan_result_id_scan_results'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setup_instance_id'], ['setup_instances.id'], name=op.f('fk_setup_condition_results_setup_instance_id_setup_instances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_condition_id'], ['strategy_conditions.id'], name=op.f('fk_setup_condition_results_strategy_condition_id_strategy_conditions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setup_condition_results')),
    sa.UniqueConstraint('setup_instance_id', 'scan_result_id', 'condition_key', name='uq_setup_condition_proof')
    )
    with op.batch_alter_table('setup_condition_results', schema=None) as batch_op:
        batch_op.create_index('ix_condition_result_setup_evaluated', ['setup_instance_id', 'evaluated_at'], unique=False)

    op.create_table('setup_lifecycle_events',
    sa.Column('setup_instance_id', sa.Uuid(), nullable=False),
    sa.Column('from_state', sa.Enum('detected', 'forming', 'near_confirmation', 'confirmed', 'entry_zone_active', 'entry_zone_missed', 'invalidated', 'expired', 'target_reached', 'stop_level_reached', 'closed', name='setup_from_state', native_enum=False), nullable=True),
    sa.Column('to_state', sa.Enum('detected', 'forming', 'near_confirmation', 'confirmed', 'entry_zone_active', 'entry_zone_missed', 'invalidated', 'expired', 'target_reached', 'stop_level_reached', 'closed', name='setup_to_state', native_enum=False), nullable=False),
    sa.Column('reason_code', sa.String(length=100), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['setup_instance_id'], ['setup_instances.id'], name=op.f('fk_setup_lifecycle_events_setup_instance_id_setup_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setup_lifecycle_events'))
    )
    with op.batch_alter_table('setup_lifecycle_events', schema=None) as batch_op:
        batch_op.create_index('ix_lifecycle_setup_occurred', ['setup_instance_id', 'occurred_at'], unique=False)

    op.create_table('alert_deliveries',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.Enum('telegram', 'discord', 'web', name='delivery_channel', native_enum=False), nullable=False),
    sa.Column('destination_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', 'suppressed', name='delivery_status', native_enum=False), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_error_detail', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_deliveries_alert_id_alerts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_deliveries')),
    sa.UniqueConstraint('alert_id', 'channel', 'destination_key', name='uq_alert_destination')
    )
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_delivery_status_retry', ['status', 'next_retry_at'], unique=False)

    op.create_table('user_feedback',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('setup_instance_id', sa.Uuid(), nullable=True),
    sa.Column('feedback_type', sa.String(length=40), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_user_feedback_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['setup_instance_id'], ['setup_instances.id'], name=op.f('fk_user_feedback_setup_instance_id_setup_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_feedback_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_feedback'))
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_feedback_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_alert_id'), ['alert_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_alert_id'))
        batch_op.drop_index('ix_feedback_user_created')

    op.drop_table('user_feedback')
    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_status_retry')

    op.drop_table('alert_deliveries')
    with op.batch_alter_table('setup_lifecycle_events', schema=None) as batch_op:
        batch_op.drop_index('ix_lifecycle_setup_occurred')

    op.drop_table('setup_lifecycle_events')
    with op.batch_alter_table('setup_condition_results', schema=None) as batch_op:
        batch_op.drop_index('ix_condition_result_setup_evaluated')

    op.drop_table('setup_condition_results')
    with op.batch_alter_table('near_miss_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_near_miss_version_score')
        batch_op.drop_index('ix_near_miss_market_captured')

    op.drop_table('near_miss_snapshots')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_user_created')
        batch_op.drop_index('ix_alert_setup_type')

    op.drop_table('alerts')
    with op.batch_alter_table('setup_instances', schema=None) as batch_op:
        batch_op.drop_index('ix_setup_user_market')
        batch_op.drop_index('ix_setup_strategy_state')
        batch_op.drop_index(batch_op.f('ix_setup_instances_expires_at'))

    op.drop_table('setup_instances')
    with op.batch_alter_table('scan_results', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_result_version_candle')
        batch_op.drop_index('ix_scan_result_outcome_score')

    op.drop_table('scan_results')
    op.drop_table('strategy_universes')
    with op.batch_alter_table('strategy_conditions', schema=None) as batch_op:
        batch_op.drop_index('ix_condition_version_parent')

    op.drop_table('strategy_conditions')
    with op.batch_alter_table('scan_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_scan_job_version_created')
        batch_op.drop_index('ix_scan_job_status_scheduled')

    op.drop_table('scan_jobs')
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trials_ends_at'))
        batch_op.drop_index('ix_trial_user_status')

    op.drop_table('trials')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_constraint(
            op.f('fk_strategies_active_version_id_strategy_versions'),
            type_='foreignkey',
        )

    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_version_status')
        batch_op.drop_index('ix_strategy_schema_hash')

    op.drop_table('strategy_versions')
    with op.batch_alter_table('identity_link_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_link_token_user_expiry')

    op.drop_table('identity_link_tokens')
    with op.batch_alter_table('disclaimer_acceptances', schema=None) as batch_op:
        batch_op.drop_index('ix_disclaimer_user_accepted')

    op.drop_table('disclaimer_acceptances')
    with op.batch_alter_table('attribution_touches', schema=None) as batch_op:
        batch_op.drop_index('ix_attribution_user_created')
        batch_op.drop_index(batch_op.f('ix_attribution_touches_user_id'))
        batch_op.drop_index(batch_op.f('ix_attribution_touches_source'))
        batch_op.drop_index(batch_op.f('ix_attribution_touches_referral_code'))
        batch_op.drop_index(batch_op.f('ix_attribution_touches_onboarding_session_id'))
        batch_op.drop_index(batch_op.f('ix_attribution_touches_campaign'))

    op.drop_table('attribution_touches')
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index('ix_user_identities_user_provider')
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))

    op.drop_table('user_identities')
    op.drop_table('telegram_connections')
    with op.batch_alter_table('support_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_support_user_created')
        batch_op.drop_index('ix_support_status_priority')

    op.drop_table('support_requests')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_provider_customer_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_current_period_end'))
        batch_op.drop_index('ix_subscription_user_status')

    op.drop_table('subscriptions')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index('ix_strategy_user_status')

    op.drop_table('strategies')
    with op.batch_alter_table('referral_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_codes_owner_user_id'))

    op.drop_table('referral_codes')
    with op.batch_alter_table('onboarding_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_onboarding_user_status')
        batch_op.drop_index('ix_onboarding_updated')

    op.drop_table('onboarding_sessions')
    with op.batch_alter_table('discord_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_discord_connections_user_id'))

    op.drop_table('discord_connections')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index('ix_billing_user_created')
        batch_op.drop_index(batch_op.f('ix_billing_events_processing_status'))
        batch_op.drop_index(batch_op.f('ix_billing_events_event_type'))

    op.drop_table('billing_events')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_target')
        batch_op.drop_index('ix_audit_request')
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('ix_audit_actor_created')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_status'))

    op.drop_table('users')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_is_active'))

    op.drop_table('plans')
    with op.batch_alter_table('market_data_health', schema=None) as batch_op:
        batch_op.drop_index('ix_market_health_status_checked')

    op.drop_table('market_data_health')
    with op.batch_alter_table('integration_health', schema=None) as batch_op:
        batch_op.drop_index('ix_integration_health_status_checked')

    op.drop_table('integration_health')
    # ### end Alembic commands ###
