"""add SC Malaysia governance workflow

Revision ID: d6e7f8a9b0c1
Revises: c5d6e7f8a9b0
Create Date: 2026-07-15 22:19:20.314826
"""

from collections.abc import Sequence
from datetime import UTC, datetime
from uuid import uuid4

import sqlalchemy as sa

from alembic import op

revision: str = "d6e7f8a9b0c1"
down_revision: str | None = "c5d6e7f8a9b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "canonical_assets",
        sa.Column("symbol", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("asset_type", sa.String(length=32), nullable=False),
        sa.Column("native_chain", sa.String(length=120), nullable=True),
        sa.Column("contract_addresses", sa.JSON(), nullable=False),
        sa.Column("official_website", sa.String(length=1000), nullable=True),
        sa.Column("official_documentation", sa.String(length=1000), nullable=True),
        sa.Column("provider_ids", sa.JSON(), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("mapping_state", sa.String(length=32), nullable=False),
        sa.Column("mapping_evidence", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_canonical_assets")),
        sa.UniqueConstraint("identity_hash", name="uq_canonical_asset_identity_hash"),
    )
    with op.batch_alter_table("canonical_assets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_canonical_asset_symbol_state", ["symbol", "mapping_state"], unique=False
        )

    op.create_table(
        "sharia_methodology_families",
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("authority", sa.String(length=240), nullable=False),
        sa.Column("regulatory_scope", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharia_methodology_families")),
        sa.UniqueConstraint("code", name=op.f("uq_sharia_methodology_families_code")),
    )
    op.create_table(
        "exchange_markets",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("exchange", sa.String(length=40), nullable=False),
        sa.Column("market_symbol", sa.String(length=60), nullable=False),
        sa.Column("base_asset", sa.String(length=32), nullable=False),
        sa.Column("quote_asset", sa.String(length=32), nullable=False),
        sa.Column("market_type", sa.String(length=20), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("metadata_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_exchange_markets_canonical_asset_id_canonical_assets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exchange_markets")),
        sa.UniqueConstraint("exchange", "market_symbol", name="uq_exchange_market_symbol"),
    )
    with op.batch_alter_table("exchange_markets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_exchange_market_asset_active", ["canonical_asset_id", "is_active"], unique=False
        )

    op.create_table(
        "official_sources",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("normalized_url", sa.String(length=1000), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("verification_state", sa.String(length=32), nullable=False),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_official_sources_canonical_asset_id_canonical_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("fk_official_sources_verified_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_official_sources")),
        sa.UniqueConstraint(
            "canonical_asset_id", "normalized_url", name="uq_official_source_asset_url"
        ),
    )
    with op.batch_alter_table("official_sources", schema=None) as batch_op:
        batch_op.create_index(
            "ix_official_source_asset_priority", ["canonical_asset_id", "priority"], unique=False
        )

    op.create_table(
        "sharia_monitoring_runs",
        sa.Column("run_kind", sa.String(length=40), nullable=False),
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("items_attempted", sa.Integer(), nullable=False),
        sa.Column("items_succeeded", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("result_summary", sa.JSON(), nullable=False),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_sharia_monitoring_runs_canonical_asset_id_canonical_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharia_monitoring_runs")),
        sa.UniqueConstraint("idempotency_key", name="uq_sharia_monitoring_run_key"),
    )
    with op.batch_alter_table("sharia_monitoring_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sharia_monitoring_run_kind_status",
            ["run_kind", "status", "created_at"],
            unique=False,
        )

    op.create_table(
        "source_snapshots",
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("official_source_id", sa.Uuid(), nullable=True),
        sa.Column("previous_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("etag", sa.String(length=500), nullable=True),
        sa.Column("last_modified", sa.String(length=500), nullable=True),
        sa.Column("response_headers", sa.JSON(), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("headings", sa.JSON(), nullable=False),
        sa.Column("source_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("meaningful_diff", sa.JSON(), nullable=False),
        sa.Column("is_material_change", sa.Boolean(), nullable=False),
        sa.Column("fetch_status", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("scraper_version", sa.String(length=80), nullable=False),
        sa.Column("parser_result", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["sharia_monitoring_runs.id"],
            name=op.f("fk_source_snapshots_monitoring_run_id_sharia_monitoring_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["official_source_id"],
            ["official_sources.id"],
            name=op.f("fk_source_snapshots_official_source_id_official_sources"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["previous_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_source_snapshots_previous_snapshot_id_source_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_snapshots")),
        sa.UniqueConstraint(
            "monitoring_run_id", "source_url", "content_hash", name="uq_source_snapshot_run_hash"
        ),
    )
    with op.batch_alter_table("source_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_source_snapshot_official_retrieved",
            ["official_source_id", "retrieved_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_source_snapshot_status_retrieved", ["fetch_status", "retrieved_at"], unique=False
        )

    op.create_table(
        "external_assessments",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=True),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("source_authority", sa.String(length=300), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("asset_name", sa.String(length=160), nullable=False),
        sa.Column("asset_symbol", sa.String(length=32), nullable=False),
        sa.Column("exact_status_wording", sa.String(length=160), nullable=False),
        sa.Column("sac_meeting_number", sa.String(length=80), nullable=False),
        sa.Column("decision_date", sa.Date(), nullable=False),
        sa.Column("regulatory_scope", sa.Text(), nullable=False),
        sa.Column("retrieval_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exact_row_text", sa.Text(), nullable=False),
        sa.Column("import_hash", sa.String(length=64), nullable=False),
        sa.Column("mapping_state", sa.String(length=32), nullable=False),
        sa.Column("mapping_notes", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_external_assessments_canonical_asset_id_canonical_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_external_assessments_source_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_assessments")),
        sa.UniqueConstraint("import_hash", name="uq_external_assessment_import_hash"),
    )
    with op.batch_alter_table("external_assessments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_external_assessment_symbol_state", ["asset_symbol", "mapping_state"], unique=False
        )

    op.create_table(
        "asset_research_dossiers",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("external_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("monitoring_run_id", sa.Uuid(), nullable=False),
        sa.Column("run_key", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("source_snapshot_ids", sa.JSON(), nullable=False),
        sa.Column("evidence_completeness", sa.Float(), nullable=False),
        sa.Column("missing_information_count", sa.Integer(), nullable=False),
        sa.Column("contradiction_count", sa.Integer(), nullable=False),
        sa.Column("evidence_package_hash", sa.String(length=64), nullable=False),
        sa.Column("factual_profile", sa.JSON(), nullable=False),
        sa.Column("limitations", sa.JSON(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_asset_research_dossiers_canonical_asset_id_canonical_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["external_assessment_id"],
            ["external_assessments.id"],
            name=op.f("fk_asset_research_dossiers_external_assessment_id_external_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["monitoring_run_id"],
            ["sharia_monitoring_runs.id"],
            name=op.f("fk_asset_research_dossiers_monitoring_run_id_sharia_monitoring_runs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_research_dossiers")),
        sa.UniqueConstraint("run_key", name="uq_asset_research_dossier_run_key"),
    )
    with op.batch_alter_table("asset_research_dossiers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_asset_research_asset_state",
            ["canonical_asset_id", "state", "created_at"],
            unique=False,
        )

    op.create_table(
        "asset_evidence_records",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("dossier_id", sa.Uuid(), nullable=False),
        sa.Column("source_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("claim_summary", sa.Text(), nullable=False),
        sa.Column("evidence_excerpt", sa.Text(), nullable=False),
        sa.Column("source_locator", sa.String(length=500), nullable=True),
        sa.Column("evidence_hash", sa.String(length=64), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_asset_evidence_records_canonical_asset_id_canonical_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["asset_research_dossiers.id"],
            name=op.f("fk_asset_evidence_records_dossier_id_asset_research_dossiers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_asset_evidence_records_source_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_asset_evidence_records")),
        sa.UniqueConstraint(
            "dossier_id", "source_snapshot_id", "evidence_hash", name="uq_asset_evidence_hash"
        ),
    )
    with op.batch_alter_table("asset_evidence_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_asset_evidence_asset_category", ["canonical_asset_id", "category"], unique=False
        )

    op.create_table(
        "sharia_ai_analysis_snapshots",
        sa.Column("dossier_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_version", sa.Integer(), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("reasoning_effort", sa.String(length=20), nullable=False),
        sa.Column("requested_service_tier", sa.String(length=20), nullable=False),
        sa.Column("returned_service_tier", sa.String(length=20), nullable=True),
        sa.Column("prompt_version", sa.String(length=80), nullable=False),
        sa.Column("input_snapshot_ids", sa.JSON(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["asset_research_dossiers.id"],
            name=op.f("fk_sharia_ai_analysis_snapshots_dossier_id_asset_research_dossiers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharia_ai_analysis_snapshots")),
        sa.UniqueConstraint("dossier_id", "analysis_version", name="uq_sharia_ai_dossier_version"),
    )
    with op.batch_alter_table("sharia_ai_analysis_snapshots", schema=None) as batch_op:
        batch_op.create_index("ix_sharia_ai_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "sharia_review_cases",
        sa.Column("case_reference", sa.String(length=40), nullable=False),
        sa.Column("case_type", sa.String(length=40), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("publication_state", sa.String(length=32), nullable=False),
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=True),
        sa.Column("external_assessment_id", sa.Uuid(), nullable=True),
        sa.Column("dossier_id", sa.Uuid(), nullable=True),
        sa.Column("methodology_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("risk_severity", sa.String(length=20), nullable=False),
        sa.Column("human_review_reason", sa.Text(), nullable=False),
        sa.Column("requested_evidence", sa.JSON(), nullable=False),
        sa.Column("admin_notes", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("last_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_reminder_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("done_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_sharia_review_cases_canonical_asset_id_canonical_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["asset_research_dossiers.id"],
            name=op.f("fk_sharia_review_cases_dossier_id_asset_research_dossiers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_assessment_id"],
            ["external_assessments.id"],
            name=op.f("fk_sharia_review_cases_external_assessment_id_external_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["methodology_id"],
            ["sharia_methodologies.id"],
            name=op.f("fk_sharia_review_cases_methodology_id_sharia_methodologies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharia_review_cases")),
        sa.UniqueConstraint("case_reference", name=op.f("uq_sharia_review_cases_case_reference")),
        sa.UniqueConstraint("idempotency_key", name="uq_sharia_review_case_key"),
    )
    with op.batch_alter_table("sharia_review_cases", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sharia_review_asset", ["canonical_asset_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_sharia_review_queue", ["state", "case_type", "created_at"], unique=False
        )

    op.create_table(
        "sharia_review_decisions",
        sa.Column("review_case_id", sa.Uuid(), nullable=False),
        sa.Column("admin_user_id", sa.Uuid(), nullable=False),
        sa.Column("methodology_id", sa.Uuid(), nullable=True),
        sa.Column("decision", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("evidence_snapshot_ids", sa.JSON(), nullable=False),
        sa.Column("decision_version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
            name=op.f("fk_sharia_review_decisions_admin_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["methodology_id"],
            ["sharia_methodologies.id"],
            name=op.f("fk_sharia_review_decisions_methodology_id_sharia_methodologies"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["sharia_review_cases.id"],
            name=op.f("fk_sharia_review_decisions_review_case_id_sharia_review_cases"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharia_review_decisions")),
        sa.UniqueConstraint(
            "review_case_id", "decision_version", name="uq_review_decision_version"
        ),
    )
    with op.batch_alter_table("sharia_review_decisions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_review_decision_case_created", ["review_case_id", "created_at"], unique=False
        )

    op.create_table(
        "sharia_telegram_notification_attempts",
        sa.Column("review_case_id", sa.Uuid(), nullable=True),
        sa.Column("notification_type", sa.String(length=40), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("chat_id", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("provider_message_id", sa.String(length=120), nullable=True),
        sa.Column("last_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["sharia_review_cases.id"],
            name=op.f(
                "fk_sharia_telegram_notification_attempts_review_case_id_sharia_review_cases"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sharia_telegram_notification_attempts")),
        sa.UniqueConstraint("idempotency_key", name="uq_sharia_telegram_attempt_key"),
    )
    with op.batch_alter_table("sharia_telegram_notification_attempts", schema=None) as batch_op:
        batch_op.create_index("ix_sharia_telegram_due", ["status", "next_retry_at"], unique=False)

    op.create_table(
        "source_change_events",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("official_source_id", sa.Uuid(), nullable=False),
        sa.Column("previous_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("current_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("review_case_id", sa.Uuid(), nullable=True),
        sa.Column("change_type", sa.String(length=80), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("meaningful_diff", sa.JSON(), nullable=False),
        sa.Column("potentially_material", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("change_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_source_change_events_canonical_asset_id_canonical_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["current_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_source_change_events_current_snapshot_id_source_snapshots"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["official_source_id"],
            ["official_sources.id"],
            name=op.f("fk_source_change_events_official_source_id_official_sources"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["previous_snapshot_id"],
            ["source_snapshots.id"],
            name=op.f("fk_source_change_events_previous_snapshot_id_source_snapshots"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["review_case_id"],
            ["sharia_review_cases.id"],
            name=op.f("fk_source_change_events_review_case_id_sharia_review_cases"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_change_events")),
        sa.UniqueConstraint("change_hash", name="uq_source_change_hash"),
    )
    with op.batch_alter_table("source_change_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_source_change_asset_severity",
            ["canonical_asset_id", "severity", "created_at"],
            unique=False,
        )

    op.create_table(
        "published_asset_assessments",
        sa.Column("canonical_asset_id", sa.Uuid(), nullable=False),
        sa.Column("external_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("dossier_id", sa.Uuid(), nullable=False),
        sa.Column("review_decision_id", sa.Uuid(), nullable=False),
        sa.Column("asset_assessment_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("publication_state", sa.String(length=32), nullable=False),
        sa.Column("passport_snapshot", sa.JSON(), nullable=False),
        sa.Column("integrity_hash", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("published_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_assessment_id"],
            ["asset_sharia_assessments.id"],
            name=op.f(
                "fk_published_asset_assessments_asset_assessment_id_asset_sharia_assessments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["canonical_asset_id"],
            ["canonical_assets.id"],
            name=op.f("fk_published_asset_assessments_canonical_asset_id_canonical_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["dossier_id"],
            ["asset_research_dossiers.id"],
            name=op.f("fk_published_asset_assessments_dossier_id_asset_research_dossiers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["external_assessment_id"],
            ["external_assessments.id"],
            name=op.f("fk_published_asset_assessments_external_assessment_id_external_assessments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["published_by_user_id"],
            ["users.id"],
            name=op.f("fk_published_asset_assessments_published_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["review_decision_id"],
            ["sharia_review_decisions.id"],
            name=op.f("fk_published_asset_assessments_review_decision_id_sharia_review_decisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_published_asset_assessments")),
        sa.UniqueConstraint("canonical_asset_id", "version", name="uq_published_asset_version"),
        sa.UniqueConstraint(
            "integrity_hash", name=op.f("uq_published_asset_assessments_integrity_hash")
        ),
    )
    with op.batch_alter_table("published_asset_assessments", schema=None) as batch_op:
        batch_op.create_index(
            "ix_published_asset_active", ["canonical_asset_id", "is_active"], unique=False
        )

    with op.batch_alter_table("sharia_methodologies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("family_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_sharia_methodologies_family_id_sharia_methodology_families"),
            "sharia_methodology_families",
            ["family_id"],
            ["id"],
            ondelete="SET NULL",
        )

    family_id = uuid4()
    methodology_id = uuid4()
    now = datetime.now(UTC)
    families = sa.table(
        "sharia_methodology_families",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("authority", sa.String()),
        sa.column("regulatory_scope", sa.Text()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    methodologies = sa.table(
        "sharia_methodologies",
        sa.column("id", sa.Uuid()),
        sa.column("family_id", sa.Uuid()),
        sa.column("code", sa.String()),
        sa.column("name", sa.String()),
        sa.column("version", sa.String()),
        sa.column("description", sa.Text()),
        sa.column("status", sa.String()),
        sa.column("governing_body", sa.String()),
        sa.column("reviewer_group", sa.String()),
        sa.column("published_at", sa.DateTime(timezone=True)),
        sa.column("effective_from", sa.DateTime(timezone=True)),
        sa.column("rules_json", sa.JSON()),
        sa.column("evidence_requirements_json", sa.JSON()),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    op.bulk_insert(
        families,
        [
            {
                "id": family_id,
                "code": "SC_MALAYSIA_SAC",
                "name": "SC Malaysia SAC Digital Assets Reference",
                "authority": "Shariah Advisory Council of the Securities Commission Malaysia",
                "regulatory_scope": (
                    "Securities Commission Malaysia regulated digital-assets framework"
                ),
                "is_active": True,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )
    op.bulk_insert(
        methodologies,
        [
            {
                "id": methodology_id,
                "family_id": family_id,
                "code": "SC_MALAYSIA_SAC_REFERENCE",
                "name": "SC Malaysia SAC reference",
                "version": "2026.03",
                "description": (
                    "Versioned record of explicit asset-level wording published by the Securities "
                    "Commission Malaysia. It is not a universal halal ruling and does not "
                    "extend to "
                    "unlisted products or uses."
                ),
                "status": "active",
                "governing_body": "Shariah Advisory Council of the Securities Commission Malaysia",
                "reviewer_group": "HilalMarkets authenticated administrators",
                "published_at": now,
                "effective_from": now,
                "rules_json": {"publication_requires_admin_approval": True, "spot_only": True},
                "evidence_requirements_json": {
                    "explicit_status_wording": True,
                    "sac_meeting_number": True,
                    "decision_date": True,
                    "source_snapshot": True,
                    "canonical_identity_verified": True,
                },
                "created_at": now,
                "updated_at": now,
            }
        ],
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DELETE FROM sharia_methodologies WHERE code = 'SC_MALAYSIA_SAC_REFERENCE'"))
    op.execute(sa.text("DELETE FROM sharia_methodology_families WHERE code = 'SC_MALAYSIA_SAC'"))
    with op.batch_alter_table("sharia_methodologies", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_sharia_methodologies_family_id_sharia_methodology_families"),
            type_="foreignkey",
        )
        batch_op.drop_column("family_id")

    with op.batch_alter_table("published_asset_assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_published_asset_active")

    op.drop_table("published_asset_assessments")
    with op.batch_alter_table("source_change_events", schema=None) as batch_op:
        batch_op.drop_index("ix_source_change_asset_severity")

    op.drop_table("source_change_events")
    with op.batch_alter_table("sharia_telegram_notification_attempts", schema=None) as batch_op:
        batch_op.drop_index("ix_sharia_telegram_due")

    op.drop_table("sharia_telegram_notification_attempts")
    with op.batch_alter_table("sharia_review_decisions", schema=None) as batch_op:
        batch_op.drop_index("ix_review_decision_case_created")

    op.drop_table("sharia_review_decisions")
    with op.batch_alter_table("sharia_review_cases", schema=None) as batch_op:
        batch_op.drop_index("ix_sharia_review_queue")
        batch_op.drop_index("ix_sharia_review_asset")

    op.drop_table("sharia_review_cases")
    with op.batch_alter_table("sharia_ai_analysis_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_sharia_ai_status_created")

    op.drop_table("sharia_ai_analysis_snapshots")
    with op.batch_alter_table("asset_evidence_records", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_evidence_asset_category")

    op.drop_table("asset_evidence_records")
    with op.batch_alter_table("asset_research_dossiers", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_research_asset_state")

    op.drop_table("asset_research_dossiers")
    with op.batch_alter_table("external_assessments", schema=None) as batch_op:
        batch_op.drop_index("ix_external_assessment_symbol_state")

    op.drop_table("external_assessments")
    with op.batch_alter_table("source_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_source_snapshot_status_retrieved")
        batch_op.drop_index("ix_source_snapshot_official_retrieved")

    op.drop_table("source_snapshots")
    with op.batch_alter_table("sharia_monitoring_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_sharia_monitoring_run_kind_status")

    op.drop_table("sharia_monitoring_runs")
    with op.batch_alter_table("official_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_official_source_asset_priority")

    op.drop_table("official_sources")
    with op.batch_alter_table("exchange_markets", schema=None) as batch_op:
        batch_op.drop_index("ix_exchange_market_asset_active")

    op.drop_table("exchange_markets")
    op.drop_table("sharia_methodology_families")
    with op.batch_alter_table("canonical_assets", schema=None) as batch_op:
        batch_op.drop_index("ix_canonical_asset_symbol_state")

    op.drop_table("canonical_assets")
    # ### end Alembic commands ###
