"""add reliability incident admin foundations

Revision ID: dedffe529345
Revises: e4280749cde8
Create Date: 2026-06-14 23:25:09.900937
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dedffe529345'
down_revision: Union[str, None] = 'e4280749cde8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('status', sa.Enum('open', 'investigating', 'mitigating', 'monitoring', 'resolved', 'cancelled', name='incident_status', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('info', 'minor', 'major', 'critical', name='incident_severity', native_enum=False), nullable=False),
    sa.Column('incident_type', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('affected_users_count', sa.Integer(), nullable=False),
    sa.Column('affected_strategies_count', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('material_user_impact', sa.String(length=32), nullable=False),
    sa.Column('mitigation_status', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('ix_incident_detected', ['detected_at'], unique=False)
        batch_op.create_index('ix_incident_status_severity', ['status', 'severity'], unique=False)

    op.create_table('operational_metrics',
    sa.Column('component', sa.String(length=60), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('healthy', 'degraded', 'down', 'unknown', name='operational_metric_status', native_enum=False), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operational_metrics'))
    )
    with op.batch_alter_table('operational_metrics', schema=None) as batch_op:
        batch_op.create_index('ix_operational_metric_component', ['component', 'metric_name', 'measured_at'], unique=False)
        batch_op.create_index('ix_operational_metric_status', ['status', 'measured_at'], unique=False)

    op.create_table('incident_updates',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('update_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('visible_to_users', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_incident_updates_author_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_updates_incident_id_incidents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_updates'))
    )
    with op.batch_alter_table('incident_updates', schema=None) as batch_op:
        batch_op.create_index('ix_incident_update_created', ['incident_id', 'created_at'], unique=False)

    op.create_table('incident_impacts',
    sa.Column('incident_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_id', sa.Uuid(), nullable=True),
    sa.Column('scan_job_id', sa.Uuid(), nullable=True),
    sa.Column('alert_id', sa.Uuid(), nullable=True),
    sa.Column('integration', sa.String(length=40), nullable=True),
    sa.Column('scope_key', sa.String(length=160), nullable=True),
    sa.Column('impact_type', sa.String(length=80), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_incident_impacts_alert_id_alerts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], name=op.f('fk_incident_impacts_incident_id_incidents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_job_id'], ['scan_jobs.id'], name=op.f('fk_incident_impacts_scan_job_id_scan_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name=op.f('fk_incident_impacts_strategy_id_strategies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incident_impacts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incident_impacts'))
    )
    with op.batch_alter_table('incident_impacts', schema=None) as batch_op:
        batch_op.create_index('ix_incident_impact_incident', ['incident_id'], unique=False)
        batch_op.create_index('ix_incident_impact_strategy', ['strategy_id'], unique=False)
        batch_op.create_index('ix_incident_impact_user', ['user_id'], unique=False)

    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('pending', 'sent', 'delivered', 'failed', 'failed_retryable', 'failed_permanent', 'suppressed', 'cancelled', name='delivery_status', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('market_data_health', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider', sa.String(length=40), server_default='ccxt', nullable=False))
        batch_op.add_column(sa.Column('symbol', sa.String(length=40), server_default='*', nullable=False))
        batch_op.add_column(sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('data_age_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('candle_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('duplicate_candle_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('out_of_order_candle_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('source_status', sa.String(length=40), server_default='unknown', nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_market_health_scope'), type_='unique')
        batch_op.create_unique_constraint('uq_market_health_scope', ['provider', 'exchange', 'symbol', 'timeframe'])
        batch_op.create_index('ix_market_health_market_checked', ['exchange', 'symbol', 'timeframe', 'checked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('market_data_health', schema=None) as batch_op:
        batch_op.drop_index('ix_market_health_market_checked')
        batch_op.drop_constraint('uq_market_health_scope', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_market_health_scope'), ['exchange', 'market_type', 'timeframe'])
        batch_op.drop_column('source_status')
        batch_op.drop_column('out_of_order_candle_count')
        batch_op.drop_column('duplicate_candle_count')
        batch_op.drop_column('candle_count')
        batch_op.drop_column('data_age_seconds')
        batch_op.drop_column('retrieved_at')
        batch_op.drop_column('symbol')
        batch_op.drop_column('provider')

    with op.batch_alter_table('alert_deliveries', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'sent', 'delivered', 'failed', 'failed_retryable', 'failed_permanent', 'suppressed', 'cancelled', name='delivery_status', native_enum=False),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('incident_impacts', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_impact_user')
        batch_op.drop_index('ix_incident_impact_strategy')
        batch_op.drop_index('ix_incident_impact_incident')

    op.drop_table('incident_impacts')
    with op.batch_alter_table('incident_updates', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_update_created')

    op.drop_table('incident_updates')
    with op.batch_alter_table('operational_metrics', schema=None) as batch_op:
        batch_op.drop_index('ix_operational_metric_status')
        batch_op.drop_index('ix_operational_metric_component')

    op.drop_table('operational_metrics')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_status_severity')
        batch_op.drop_index('ix_incident_detected')

    op.drop_table('incidents')
    # ### end Alembic commands ###
