"""add discord billing entitlement foundations

Revision ID: e4280749cde8
Revises: e4f4e4c84d0c
Create Date: 2026-06-14 23:06:49.705226
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4280749cde8'
down_revision: Union[str, None] = 'e4f4e4c84d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_role_mappings',
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('role_name', sa.String(length=80), nullable=False),
    sa.Column('entitlement_key', sa.String(length=80), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_role_mappings')),
    sa.UniqueConstraint('guild_id', 'role_id', 'entitlement_key', name='uq_discord_role_map')
    )
    op.create_table('admin_overrides',
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('override_type', sa.String(length=60), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name=op.f('fk_admin_overrides_admin_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_admin_overrides_target_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_overrides'))
    )
    with op.batch_alter_table('admin_overrides', schema=None) as batch_op:
        batch_op.create_index('ix_admin_override_admin_created', ['admin_user_id', 'created_at'], unique=False)
        batch_op.create_index('ix_admin_override_target', ['target_user_id', 'override_type'], unique=False)

    op.create_table('discord_guild_installations',
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('guild_name', sa.String(length=160), nullable=True),
    sa.Column('installed_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('bot_permissions', sa.JSON(), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_permission_check_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['installed_by_user_id'], ['users.id'], name=op.f('fk_discord_guild_installations_installed_by_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_guild_installations')),
    sa.UniqueConstraint('guild_id', name='uq_discord_guild_installation')
    )
    op.create_table('discord_oauth_states',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('state_digest', sa.String(length=64), nullable=False),
    sa.Column('redirect_url', sa.String(length=1000), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discord_oauth_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_oauth_states')),
    sa.UniqueConstraint('state_digest', name='uq_discord_oauth_state_digest')
    )
    with op.batch_alter_table('discord_oauth_states', schema=None) as batch_op:
        batch_op.create_index('ix_discord_oauth_user_expiry', ['user_id', 'expires_at'], unique=False)

    op.create_table('discord_role_sync_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('role_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discord_role_sync_jobs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_role_sync_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_discord_role_sync_idempotency')
    )
    with op.batch_alter_table('discord_role_sync_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_discord_role_sync_status_retry', ['status', 'next_retry_at'], unique=False)

    op.create_table('entitlement_snapshots',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_entitlement_snapshots_plan_id_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_entitlement_snapshots_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entitlement_snapshots'))
    )
    with op.batch_alter_table('entitlement_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_entitlement_user_period', ['user_id', 'starts_at', 'ends_at'], unique=False)
        batch_op.create_index('ix_entitlement_user_status', ['user_id', 'status'], unique=False)

    op.create_table('usage_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_type', sa.String(length=60), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_records')),
    sa.UniqueConstraint('idempotency_key', name='uq_usage_idempotency_key')
    )
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.create_index('ix_usage_user_metric_period', ['user_id', 'metric', 'period_start'], unique=False)

    op.create_table('discord_delivery_destinations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('guild_installation_id', sa.Uuid(), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('discord_user_id', sa.String(length=64), nullable=True),
    sa.Column('guild_id', sa.String(length=64), nullable=True),
    sa.Column('channel_id', sa.String(length=64), nullable=True),
    sa.Column('thread_policy', sa.String(length=32), nullable=False),
    sa.Column('permissions_status', sa.String(length=32), nullable=False),
    sa.Column('test_status', sa.String(length=32), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['guild_installation_id'], ['discord_guild_installations.id'], name=op.f('fk_discord_delivery_destinations_guild_installation_id_discord_guild_installations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discord_delivery_destinations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_delivery_destinations')),
    sa.UniqueConstraint('user_id', 'mode', 'guild_id', 'channel_id', name='uq_discord_destination_scope')
    )
    with op.batch_alter_table('discord_delivery_destinations', schema=None) as batch_op:
        batch_op.create_index('ix_discord_destination_user_status', ['user_id', 'status'], unique=False)

    op.create_table('referral_relationships',
    sa.Column('referrer_user_id', sa.Uuid(), nullable=False),
    sa.Column('referred_user_id', sa.Uuid(), nullable=False),
    sa.Column('referral_code_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reward_status', sa.String(length=32), nullable=False),
    sa.Column('reward_granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referral_codes.id'], name=op.f('fk_referral_relationships_referral_code_id_referral_codes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name=op.f('fk_referral_relationships_referred_user_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name=op.f('fk_referral_relationships_referrer_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_referral_relationships')),
    sa.UniqueConstraint('referred_user_id', name='uq_referral_referred_user')
    )
    with op.batch_alter_table('referral_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_referral_referrer_status', ['referrer_user_id', 'status'], unique=False)

    op.create_table('discord_setup_threads',
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('setup_instance_id', sa.Uuid(), nullable=True),
    sa.Column('strategy_version_id', sa.Uuid(), nullable=False),
    sa.Column('setup_key', sa.String(length=160), nullable=False),
    sa.Column('thread_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_message_id', sa.String(length=64), nullable=True),
    sa.Column('last_message_id', sa.String(length=64), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['discord_delivery_destinations.id'], name=op.f('fk_discord_setup_threads_destination_id_discord_delivery_destinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['setup_instance_id'], ['setup_instances.id'], name=op.f('fk_discord_setup_threads_setup_instance_id_setup_instances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], name=op.f('fk_discord_setup_threads_strategy_version_id_strategy_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_setup_threads')),
    sa.UniqueConstraint('destination_id', 'setup_key', name='uq_discord_setup_thread')
    )
    with op.batch_alter_table('discord_setup_threads', schema=None) as batch_op:
        batch_op.create_index('ix_discord_thread_strategy', ['strategy_version_id', 'setup_key'], unique=False)

    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('eligible', 'activated', 'active', 'ending_soon', 'converted', 'expired', 'canceled', 'blocked', 'manually_extended', name='trial_status', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trials', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('eligible', 'activated', 'active', 'ending_soon', 'converted', 'expired', 'canceled', 'blocked', 'manually_extended', name='trial_status', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('discord_setup_threads', schema=None) as batch_op:
        batch_op.drop_index('ix_discord_thread_strategy')

    op.drop_table('discord_setup_threads')
    with op.batch_alter_table('referral_relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_referral_referrer_status')

    op.drop_table('referral_relationships')
    with op.batch_alter_table('discord_delivery_destinations', schema=None) as batch_op:
        batch_op.drop_index('ix_discord_destination_user_status')

    op.drop_table('discord_delivery_destinations')
    with op.batch_alter_table('usage_records', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_user_metric_period')

    op.drop_table('usage_records')
    with op.batch_alter_table('entitlement_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_entitlement_user_status')
        batch_op.drop_index('ix_entitlement_user_period')

    op.drop_table('entitlement_snapshots')
    with op.batch_alter_table('discord_role_sync_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_discord_role_sync_status_retry')

    op.drop_table('discord_role_sync_jobs')
    with op.batch_alter_table('discord_oauth_states', schema=None) as batch_op:
        batch_op.drop_index('ix_discord_oauth_user_expiry')

    op.drop_table('discord_oauth_states')
    op.drop_table('discord_guild_installations')
    with op.batch_alter_table('admin_overrides', schema=None) as batch_op:
        batch_op.drop_index('ix_admin_override_target')
        batch_op.drop_index('ix_admin_override_admin_created')

    op.drop_table('admin_overrides')
    op.drop_table('discord_role_mappings')
    # ### end Alembic commands ###

