"""add telegram conversations and engine states

Revision ID: e4f4e4c84d0c
Revises: 5aa448aa1447
Create Date: 2026-06-14 22:20:56.437913
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4f4e4c84d0c'
down_revision: Union[str, None] = '5aa448aa1447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_callback_receipts',
    sa.Column('callback_query_id', sa.String(length=128), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_callback_receipts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_callback_receipts')),
    sa.UniqueConstraint('callback_query_id', name='uq_telegram_callback_query')
    )
    with op.batch_alter_table('telegram_callback_receipts', schema=None) as batch_op:
        batch_op.create_index('ix_telegram_callback_user_created', ['telegram_user_id', 'created_at'], unique=False)

    op.create_table('telegram_conversation_states',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('onboarding_session_id', sa.Uuid(), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=False),
    sa.Column('chat_id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('flow', sa.String(length=64), nullable=False),
    sa.Column('step', sa.String(length=64), nullable=False),
    sa.Column('state_data', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('last_message_id', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['onboarding_session_id'], ['onboarding_sessions.id'], name=op.f('fk_telegram_conversation_states_onboarding_session_id_onboarding_sessions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_conversation_states_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_conversation_states')),
    sa.UniqueConstraint('telegram_user_id', name='uq_telegram_conversation_user')
    )
    with op.batch_alter_table('telegram_conversation_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_conversation_states_onboarding_session_id'), ['onboarding_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegram_conversation_states_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_telegram_conversation_user_flow', ['user_id', 'flow', 'step'], unique=False)

    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('draft', 'forward_test', 'active', 'paused', 'archived', name='strategy_status', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('draft', 'forward_test', 'active', 'paused', 'archived', name='strategy_status', native_enum=False),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    with op.batch_alter_table('telegram_conversation_states', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_conversation_user_flow')
        batch_op.drop_index(batch_op.f('ix_telegram_conversation_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_conversation_states_onboarding_session_id'))

    op.drop_table('telegram_conversation_states')
    with op.batch_alter_table('telegram_callback_receipts', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_callback_user_created')

    op.drop_table('telegram_callback_receipts')
    # ### end Alembic commands ###

